# TOOD:
# Change to docker compose
# Run tests

image: docker

services:
  - docker:dind
  
cache:
  key: ${CI_COMMIT_REF_SLUG}

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  
build-master:
    only: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_PROJECT_NAME:latest"
    stage: build
    script:
        - docker build -t  index.docker.io/polyswarm/polyswarm-contracts .
        - docker-compose up -d geth
        - docker-compose up --exit-code-from polyswarm-contracts
        - docker-compose down
        - docker login -u "$CI_CUSTOM_DOCKER_HUB_USERNAME" -p "$CI_CUSTOM_DOCKER_HUB_USERNAME" $CI_CUSTOM_DOCKER_HUB_URI && docker push index.docker.io/polyswarm/polyswarm-contracts


build-non-master:
    except: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    stage: build
    script:
        - docker build -t $DOCKER_FULL_PATH .
        - docker-compose up -d geth
        - docker-compose up --exit-code-from polyswarm-contracts
        - docker-compose down
