image: docker:stable

services:
  - docker:dind

before_script:
  - apk --no-cache add curl pip
  - pip install docker-compose

build-docker:
    tags:
        - docker
    stage: test
    script: 
        - docker build -t ${CI_PROJECT_PATH} -f docker/Dockerfile .
        - docker-compose up -d geth
        - docker-compose up --exit-code-from polyswarm-contracts
        - docker-compose down
        
kick-e2e:
    only: 
        - master
    tags:
        - docker
    stage: deploy
    script:
       - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.polyswarm.io/api/v4/projects/${CI_CUSTOM_PROJECT_ID_META}/trigger/pipeline

