version: '3'
services:
    polyswarm-contracts:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - geth
        environment:
            - geth=geth
            - port=9545
        ports:
            - "31337:31337"
        volumes:
            - "./build:/build"
        command: ["./migrate_and_test.sh"]
    geth:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "8545:9545"
        logging:
            driver: none
        command: ["truffle", "develop", "--log"]
